server:
  port: 9091
  servlet:
    context-path: /nodeservice

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
    enabled: true
    
ribbon:
  eureka:
    enabled: true

spring:
  application:
    name: node-service
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  threadpool:
    default:
      maxQueueSize: 10
      queueSizeRejectionThreshold: 10

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true