server:
   port: 9090
management:
   endpoints:
      web:
         exposure:
           include: hystrix.stream
eureka:
   client:
      service-url:
         defaultZone: http://127.0.0.1:8761/eureka/
   instance:
      preferIpAddress: true
spring:
   application:
      name: zuul-api-gateway-server
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lowerCaseServiceId: true
         routes:
         - id: accountservice
           uri: lb://account-service
           predicates:
           - Path=/accountservice/**
         - id: nodeservice
           uri: lb://node-service
           predicates:
           - Path=/nodeservice/**